package org.kuali.rice.location.v2_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2018-01-21T16:05:37.361-05:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "campusService", 
                  wsdlLocation = "file:/Users/mukadder/Downloads/simpleDocumentActionsServiceClient/src/main/wsdl/identityService.wsdl",
                  targetNamespace = "http://rice.kuali.org/location/v2_0") 
public class CampusService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://rice.kuali.org/location/v2_0", "campusService");
    public final static QName CampusServicePort = new QName("http://rice.kuali.org/location/v2_0", "campusServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/mukadder/Downloads/simpleDocumentActionsServiceClient/src/main/wsdl/identityService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CampusService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/mukadder/Downloads/simpleDocumentActionsServiceClient/src/main/wsdl/identityService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CampusService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CampusService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CampusService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CampusService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CampusService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CampusService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CampusService
     */
    @WebEndpoint(name = "campusServicePort")
    public CampusService getCampusServicePort() {
        return super.getPort(CampusServicePort, CampusService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CampusService
     */
    @WebEndpoint(name = "campusServicePort")
    public CampusService getCampusServicePort(WebServiceFeature... features) {
        return super.getPort(CampusServicePort, CampusService.class, features);
    }

}
