package org.kuali.rice.location.v2_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2018-01-21T16:05:37.356-05:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://rice.kuali.org/location/v2_0", name = "campusService")
@XmlSeeAlso({org.kuali.rice.core.v2_0.ObjectFactory.class, ObjectFactory.class})
public interface CampusService {

    @WebMethod
    @RequestWrapper(localName = "findAllCampusTypes", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindAllCampusTypes")
    @ResponseWrapper(localName = "findAllCampusTypesResponse", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindAllCampusTypesResponse")
    @WebResult(name = "campusTypes", targetNamespace = "http://rice.kuali.org/location/v2_0")
    public org.kuali.rice.location.v2_0.FindAllCampusTypesResponse.CampusTypes findAllCampusTypes();

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getCampusTypeResponse", targetNamespace = "http://rice.kuali.org/location/v2_0", partName = "parameters")
    public GetCampusTypeResponse getCampusType(
        @WebParam(partName = "parameters", name = "getCampusType", targetNamespace = "http://rice.kuali.org/location/v2_0")
        GetCampusType parameters
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "findCampuses", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindCampuses")
    @ResponseWrapper(localName = "findCampusesResponse", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindCampusesResponse")
    @WebResult(name = "results", targetNamespace = "http://rice.kuali.org/location/v2_0")
    public org.kuali.rice.location.v2_0.CampusQueryResultsType findCampuses(
        @WebParam(name = "query", targetNamespace = "http://rice.kuali.org/location/v2_0")
        org.kuali.rice.core.v2_0.QueryByCriteriaType query
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @RequestWrapper(localName = "findAllCampuses", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindAllCampuses")
    @ResponseWrapper(localName = "findAllCampusesResponse", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindAllCampusesResponse")
    @WebResult(name = "campuses", targetNamespace = "http://rice.kuali.org/location/v2_0")
    public org.kuali.rice.location.v2_0.FindAllCampusesResponse.Campuses findAllCampuses();

    @WebMethod
    @RequestWrapper(localName = "findCampusTypes", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindCampusTypes")
    @ResponseWrapper(localName = "findCampusTypesResponse", targetNamespace = "http://rice.kuali.org/location/v2_0", className = "org.kuali.rice.location.v2_0.FindCampusTypesResponse")
    @WebResult(name = "results", targetNamespace = "http://rice.kuali.org/location/v2_0")
    public org.kuali.rice.location.v2_0.CampusTypeQueryResultsType findCampusTypes(
        @WebParam(name = "query", targetNamespace = "http://rice.kuali.org/location/v2_0")
        org.kuali.rice.core.v2_0.QueryByCriteriaType query
    ) throws RiceIllegalArgumentException;

    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getCampusResponse", targetNamespace = "http://rice.kuali.org/location/v2_0", partName = "parameters")
    public GetCampusResponse getCampus(
        @WebParam(partName = "parameters", name = "getCampus", targetNamespace = "http://rice.kuali.org/location/v2_0")
        GetCampus parameters
    ) throws RiceIllegalArgumentException;
}
